version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
     - 5001:5001
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      APP_NAME: "backend"
    container_name: backend-con
    env_file: ./backend/.env
    restart: always
    links:
      - db
    volumes:
      - ./backend:/backend/
    depends_on:
      - db
    networks:
      - app-tier
    tty: true

  db:
    image: mysql
    container_name: mysql-con
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app-tier
    tty: true

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx-con
    depends_on:
      - backend
    networks:
      - app-tier
    tty: true

networks:
  app-tier:
    driver: bridge

volumes:
  mysql: null
